-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.END_DATE = "2044.12.31"
NDefines.NGame.DAYS_TO_DECLARE_WA = "1"
NDefines.NGame.CLAIM_THRONE_TRUST = "75"
NDefines.NGame.NUM_POSSIBLE_RIVALS = "4"
NDefines.NGame.MAX_FREE_CITIES = "24"
NDefines.NGame.PEACE_COST_UNION = "95"
NDefines.NGame.PEACE_COST_CHANGE_GOVERNMENT = "95"
NDefines.NGame.PEACE_COST_WAR_REPARATIONS = "5"
NDefines.NGame.PEACE_COST_ENFORCED_MILITARY_ACCESS = "5"
NDefines.NGame.THREATEN_WAR_PRESTIGE = "40"
NDefines.NGame.BREAK_ALLIANCE_DISTANCE_FACTOR = "-0.1"
NDefines.NGame.AGE_USHER_IN_TIME = 180

NDefines.NCountry.FREE_IDEA_GROUP_COST  = 6

NDefines.NCountry.REVANCHISM_MONTHLY_DECAY = 0.417			-- about 20 years to decay all of it.

NDefines.NCountry.MAX_WAR_EXHAUSTION = 50

NDefines.NCountry.POWER_MAX = 1200

NDefines.NCountry.DISMANTLE_HRE_PRESTIGE = 200

NDefines.NCountry.PS_ARTILLERY_BARRAGE = 15
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_ASSAULT = 50

NDefines.NCountry.LIBERTY_DESIRE_RELATIVE_POWER = 100
NDefines.NCountry.DIVERT_TRADE_LIBERTY = 50
NDefines.NCountry.EMBARGO_RIVALS_LIBERTY = 10
NDefines.NCountry.MAX_CROWN_COLONIES = 7

NDefines.NCountry.BREAK_ALLIANCE_PRESTIGE_LOSS = 40
NDefines.NCountry.BREAK_ALLIANCE_TRUST_COST = 15

NDefines.NCountry.INNOVATIVENESS_MAX = 100
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1

NDefines.NCountry.PARLIAMENT_ISSUE_DURATION = 8				-- in years
NDefines.NCountry.PARLIAMENT_DEBATE_DURATION = 2			-- in years
NDefines.NCountry.PARLIAMENT_PRESTIGE_HIT = -5				-- penalty if failed debate.
NDefines.NCountry.PARLIAMENT_CHANCE_OF_DECISION = 10		-- % Chance debate is ended after PARLIAMENT_DEBATE_DURATION
NDefines.NCountry.PARLIAMENT_BACKING_PERCENTAGE = 40
NDefines.NCountry.DEVELOPMENT_ON_CONTINENT_FOR_NEW_CAPITAL = 0.5

NDefines.NCountry.DICTATORSHIP_TRADITION_FOR_MONARCHY = 15		-- If republican tradition is lower than this on death of ruler, dictatorship turns into monarchy
NDefines.NCountry.DICTATORSHIP_TRADITION_FOR_REPUBLIC = 50		-- If republican tradition is this or higher on death of ruler, dictatorship turns into republic
NDefines.NCountry.IDEA_TO_TECH = 0
NDefines.NCountry.TECH_TIME_COST = 0.32
NDefines.NCountry.YEARS_UNTIL_BROKEN = 1
NDefines.NCountry.AGE_OF_ADULTHOOD = 15
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 1
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 20
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 150		-- Need at least this much development to upgrade to government rank 2
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 800
NDefines.NCountry.PS_STRENGTHEN_GOVERNMENT = 60
NDefines.NCountry.CORE_LOSE = 75
NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = 200
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0.6
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 15
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 15
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 0

NDefines.NCountry.REVOLUTION_SPREAD_COUNT = 4
NDefines.NCountry.REVOLUTION_DAILY_SPREAD = 1.2
NDefines.NCountry.REVOLUTION_CLAIM_MIN_ZEAL = 1.0
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 50

NDefines.NCountry.PS_FACTION_BOOST = 500

NDefines.NCountry.OVERSEAS_CLIENT_STATES = 1

NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 1

NDefines.NCountry.PS_SCORCH_EARTH = 50

NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 10.0




NDefines.NEconomy.AUTONOMY_AT_CONQUEST = 90

NDefines.NEconomy.SPLENDOR_ABILITY_COST = 700



NDefines.NMilitary.SIEGE_ATTRITION = 4
NDefines.NMilitary.SIEGE_WIN = 19
NDefines.NMilitary.DAYS_PER_SIEGE_PHASE = 20

NDefines.NMilitary.SCORCHED_DEVASTATION_IMPACT = 25

NDefines.NMilitary.COMBAT_DICE_SIDE = 12
NDefines.NMilitary.CANNOT_RETREAT_DAYS = 7

NDefines.NMilitary.SLACKEN_AP_DROP = 0.15
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 2.5

NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 24

NDefines.NMilitary.REBEL_RELOCATION_DISTANCE_MAX = 200000

NDefines.NMilitary.REBEL_LEADER_POWER = 30


NDefines.NMilitary.MORALE_RECOVERY_SPEED = 0.1
NDefines.NMilitary.MORALE_RECOVERY_SPEED_OWN_TERRITORY = 0.35

NDefines.NMilitary.WARGOAL_MAX_BONUS = 30

NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 99

NDefines.NMilitary.MAX_REBEL_SUPPRESSION = 15.0

NDefines.NMilitary.FORT_FLIPPING_TIME = 90

NDefines.NMilitary.RIVER_CROSSING_PENALTY = -1
NDefines.NMilitary.STRAIT_CROSSING_PENALTY = -3
NDefines.NMilitary.SEA_LANDING_PENALTY = -4

NDefines.NMilitary.COMBAT_DICE_SIDE = 6





NDefines.NAI.DEVELOPMENT_CAP_BASE = 500
NDefines.NAI.DEVELOPMENT_CAP_MULT = 50
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 250

NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.25
NDefines.NAI.AGGRESSIVENESS = 300
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 600

NDefines.NAI.FOG_OF_WAR_FORGET_CHANCE = 75

NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.15
NDefines.NAI.ACCEPTABLE_BALANCE_FRIEND_IN_COMBAT = 0.35
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 250

NDefines.NAI.INVADING_MAX_AWAY_RATIO = 0.7

NDefines.NAI.RIVAL_ALLIANCE_PENALTY = 100
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0.75
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 3.0
NDefines.NAI.PEACE_CAPITAL_FACTOR = 10
NDefines.NAI.PEACE_INDEPENDENCE_FACTOR = 75
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0.35

NDefines.NDiplomacy.CHARTER_COMPANY_BASE_COST = 3000
NDefines.NDiplomacy.CHARTER_COMPANY_MINIMUM_COST = 500

NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.35
NDefines.NDiplomacy.AE_PROVINCE_CAP = 50
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 15
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 5
NDefines.NDiplomacy.CHARTER_COMPANY_BASE_COST = 500
NDefines.NDiplomacy.CHARTER_COMPANY_MINIMUM_COST = 50

NDefines.NDiplomacy.PO_FORM_PU_AE = 0.25
NDefines.NDiplomacy.PO_HUMILIATE_POWER_GAIN = 250




NDefines.NGraphics.MAX_MAPMODE_COLOR_UPDATE_DELAY_MS = 60
NDefines.NGraphics.LIGHT_DIRECTION_X = -1.0
NDefines.NGraphics.LIGHT_DIRECTION_Y = -1.0
NDefines.NGraphics.LIGHT_DIRECTION_Z = -0.5

NDefines.NGraphics.CITY_SPRAWL_AMOUNT = 1.0


NDefines.NNationDesigner.RULER_MIN_AGE = 15
NDefines.NNationDesigner.RULER_MAX_AGE = 80
NDefines.NNationDesigner.HEIR_MAX_AGE = 80
NDefines.NNationDesigner.IDEAS_MAX_LEVEL = 10
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_1 = -40
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_3 = 200
